image:  doctrine/nodejs-aws-cli

stages:
- deploy

before_script:
# - apt-get update -y
# - apt-get install build-essential awscli -y
# - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
# - unzip awscliv2.zip
# - sudo ./aws/install
- npm install -g serverless


sls_deploy:
  stage: deploy
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.presidio.com
  variables:
    ROLE_ARN: "arn:aws:iam::462238065942:role/GitLabCI"
  script:
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws sts get-caller-identity
    - echo "Installing serverless packages"
    - serverless plugin install -n serverless-webpack
    - serverless plugin install -n serverless-offline
    - echo "Deploy Serverless to AWS "
    - sls info