app: aspir-ally
service: aspir-ally
frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-offline

custom: ${file(./serverless-vars.yml)}

provider:
  name: aws
  runtime: ${self:custom.runtime}
  region: ${self:custom.region}
  timeout: 30
  tags: ${self:custom.tags}
  stage: ${opt:stage,'dev'}
  environment:
    OPENAI_API_KEY: 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
    AWS_ACCESS_KEY_ID: "fakeMyKeyId"
    AWS_SECRET_ACCESS_KEY: "fakeSecretAccessKey"
    AWS_REGION: "us-east-1"
  iam:
    role:
      name: GlobalPerFunctionRole

functions:
  - ${file(./infrastructure/functions/goal.yml)}
  - ${file(./infrastructure/functions/tech-updates.yml)}
  - ${file(./infrastructure/functions/user.yml)}

resources:
  Resources: ${file(./infrastructure/resources/serverless-cfn.yml)}
