hello:
  name: ${self:custom.projectName}-${sls:stage}-handler
  handler: ././src/api/handler.handler
  role: GlobalPerFunctionRole
  events:
    - http:
        path: api/hello
        method: get
getShortTermGoals:
  name: ${self:custom.projectName}-${sls:stage}-getShortTermGoals
  handler: ././src/api/GoalController.getShortTermGoals
  role: GlobalPerFunctionRole
  events:
    - http:
        path: api/goal/short
        method: get
getSteps:
  name: ${self:custom.projectName}-${sls:stage}-getSteps
  handler: ././src/api/GoalController.getSteps
  role: GlobalPerFunctionRole
  events:
    - http:
        path: api/goal/short/action
        method: get
getTasks:
  name: ${self:custom.projectName}-${sls:stage}-getTasks
  handler: ././src/api/GoalController.getTasks
  role: GlobalPerFunctionRole
  events:
    - http:
        path: api/goal/short/task
        method: get
getRelatedTechnologies:
  name: ${self:custom.projectName}-${sls:stage}-getRelatedTechnologies
  handler: ././src/api/GoalController.getRelatedTechnologies
  role: GlobalPerFunctionRole
  events:
    - http:
        path: api/goal/tech
        method: get
getShortTermGoalRelatedTechnologies:
  name: ${self:custom.projectName}-${sls:stage}-getShortTermGoalRelatedTechnologies
  handler: ././src/api/GoalController.getRelatedTechnologies
  role: GlobalPerFunctionRole
  events:
    - http:
        path: api/goal/short/tech
        method: get
getQuiz:
  name: ${self:custom.projectName}-${sls:stage}-getQuiz
  handler: ././src/api/GoalController.getQuiz
  role: GlobalPerFunctionRole
  events:
    - http:
        path: api/goal/short/quiz
        method: get
getQuotes:
  name: ${self:custom.projectName}-${sls:stage}-getQuotes
  handler: ././src/api/GoalController.getQuotes
  role: GlobalPerFunctionRole
  events:
    - http:
        path: api/goal/quote
        method: get