GlobalPerFunctionRole:
  Type: AWS::IAM::Role
  Properties:
    Path: /
    RoleName: ${self:custom.projectName}-${sls:stage}-lambda-execution-iam-role
    AssumeRolePolicyDocument:
      Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
      Version: "2012-10-17"
    ManagedPolicyArns:
      - Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
    Policies: ${file(./infrastructure/resources/serverless-role.yml)}
GoalTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: Id
        KeyType: HASH
    TableName: AspirAlly
